# Taps
tap "homebrew/bundle"
tap "homebrew/completions"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/versions"
tap "neovim/neovim"
tap "rogual/neovim-dot-app"
tap "yudai/gotty"

# Packages
brew "ack"
brew "awscli"
brew "ccat"
brew "coreutils"
brew "direnv"
brew "dnsmasq"
brew "dos2unix"
brew "editorconfig"
brew "gem-completion", args: ["HEAD"]
brew "git"
brew "gotty"
brew "grc"
brew "htop-osx"
brew "imagemagick"
brew "mysql"
brew "neovim"
brew "nginx"
brew "php56"
brew "php56-mcrypt"
brew "python"
brew "python3"
brew "ruby-completion", args: ["HEAD"]
brew "the_silver_searcher"
brew "tidy-html5"
brew "tmux", args: ["HEAD"]
brew "tree"
brew "unrar"
brew "unzip"
brew "vim", args: ["--with-lua", "--without-python", "--with-python3"]
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
