[[ -n "$SSH_CLIENT" ]] || export DEFAULT_USER=`whoami`
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history)
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S %Y/%m/%d}"
POWERLEVEL9K_NODE_VERSION_BACKGROUND='022'
